version: '3.4'

services:
  avatar.in.api:
    env_file:
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - /C/ei8/avatars/prod/sample:/C/db
    ports:
      - 192.168.8.131:60013:80
#  avatar.out.api:
#    env_file: 
#      - ./var1.env
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#    volumes:
#      - C:\ei8\db:C:\db
#    ports:
#      - "60031:80"