version: '3.4'

services:
  avatar.in.api:
    env_file:
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - /C/ei8/avatars/prod/sample:/C/db
    ports:
      - 0.0.0.0:60001:80
networks:
    default:
        external:
            name: sample_default