version: '3.4'

services:
  avatar.in.api:
    env_file:
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - C:\db:C:\db
    ports:
      - "60030:80"
  avatar.out.api:
    env_file: 
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - C:\db:C:\db
    ports:
      - "60031:80"
networks:
  default:
    external:
      name: nat